if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("InterventionDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4639035899476826"}),null);
__d("InterventionDialogQuery$Parameters",["InterventionDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("InterventionDialogQuery_facebookRelayOperation"),metadata:{},name:"InterventionDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGranularTimestamp.react",["fbt","CometTimestamp.react","formatDate","react","useServerTime"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react"),j=1e3*60*60,k=j*24;function l(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}function a(a){var b=a.date;a=a.granularity;a=a===void 0?"none":a;var d=c("useServerTime")();if(a==="none"||a==="min")return i.jsx(c("CometTimestamp.react"),{date:b});if(a==="hour"){var e=b.valueOf()%j;e=new Date(b.valueOf()-e);return i.jsx(c("CometTimestamp.react"),{date:e})}if(a==="year")return c("formatDate")(b,"Y");if(a==="month")return d.getFullYear()===b.getFullYear()?c("formatDate")(b,"F"):c("formatDate")(b,"F Y");if(l(b,d))return h._(/*FBT_CALL*/"Hoje"/*FBT_CALL*/);e=new Date(d.valueOf()-k);if(l(b,e))return h._(/*FBT_CALL*/"Ontem"/*FBT_CALL*/);a=new Date(d.valueOf()+k);if(l(b,a))return h._(/*FBT_CALL*/"Amanh\u00e3"/*FBT_CALL*/);return d.getFullYear()!==b.getFullYear()?c("formatDate")(b,"F j, Y"):c("formatDate")(b,"F j")}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("BusinessCometSelfViewContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(!1);c=b;g["default"]=c}),98);
__d("PagesCometLikeChainingContext.react",["emptyFunction","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");b=d("react");var i=b.useMemo,j=b.useState,k=h.createContext({setShouldShowLikeChaining:c("emptyFunction"),shouldShowLikeChaining:!1});function a(a){a=a.children;var b=j(!1),c=b[0],d=b[1];b=i(function(){return{setShouldShowLikeChaining:d,shouldShowLikeChaining:c}},[c]);return h.jsx(k.Provider,{value:b,children:a})}a.displayName=a.name+" [from "+f.id+"]";g.PagesCometLikeChainingContext=k;g.PagesCometLikeChainingContextProvider=a}),98);
__d("InterventionDialog.entrypoint",["InterventionDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{extraProps:a,queries:{InterventionDialogQueryReference:{parameters:c("InterventionDialogQuery$Parameters"),variables:{actionType:a.actionType,entityID:a.entityID,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("InterventionDialog.react").__setRef("InterventionDialog.entrypoint")};g["default"]=a}),98);
__d("CometVideoHomeRootContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({autoplay:!0,injectedVideoID:null,isFacebookReferrer:!1,qplInstanceKey:0,renderedInWatchRoot:!1});g["default"]=b}),98);
__d("LogWebMemoryUsageFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1765264");c=b("FalcoLoggerInternal").create("log_web_memory_usage",a);e.exports=c}),null);
__d("PagesPageActionClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744141");c=b("FalcoLoggerInternal").create("pages_page_action_click",a);e.exports=c}),null);
__d("PagesTypedLogger",["Banzai","GeneratedLoggerUtils","nullthrows"],(function(a,b,c,d,e,f){"use strict";a=function(){function a(){this.$1={}}var c=a.prototype;c.log=function(a){b("GeneratedLoggerUtils").log("logger:PagesLoggerConfig",this.$1,b("Banzai").BASIC,a)};c.logVital=function(a){b("GeneratedLoggerUtils").log("logger:PagesLoggerConfig",this.$1,b("Banzai").VITAL,a)};c.logImmediately=function(a){b("GeneratedLoggerUtils").log("logger:PagesLoggerConfig",this.$1,{signal:!0},a)};c.clear=function(){this.$1={};return this};c.getData=function(){return babelHelpers["extends"]({},this.$1)};c.updateData=function(a){this.$1=babelHelpers["extends"]({},this.$1,a);return this};c.setConnectionClass=function(a){this.$1.connection_class=a;return this};c.setEvent=function(a){this.$1.event=a;return this};c.setEventLocation=function(a){this.$1.event_location=a;return this};c.setEventTarget=function(a){this.$1.event_target=a;return this};c.setLogSource=function(a){this.$1.log_source=a;return this};c.setNavAttributionIDV2Key=function(a){this.$1.nav_attribution_id_v2_key=a;return this};c.setPageID=function(a){this.$1.page_id=a;return this};c.setRawClientTime=function(a){this.$1.raw_client_time=a;return this};c.setSessionid=function(a){this.$1.sessionid=a;return this};c.setTags=function(a){this.$1.tags=b("GeneratedLoggerUtils").serializeVector(a);return this};c.updateExtraData=function(a){a=b("nullthrows")(b("GeneratedLoggerUtils").serializeMap(a));b("GeneratedLoggerUtils").checkExtraDataFieldNames(a,g);this.$1=babelHelpers["extends"]({},this.$1,a);return this};c.addToExtraData=function(a,b){var c={};c[a]=b;return this.updateExtraData(c)};return a}();var g={connection_class:!0,event:!0,event_location:!0,event_target:!0,log_source:!0,nav_attribution_id_v2_key:!0,page_id:!0,raw_client_time:!0,sessionid:!0,tags:!0};f["default"]=a}),66);
__d("PagesLoggerEventEnum",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({CLICK:"click",CREATE:"create",DELETE:"delete",DRAG:"drag",HOVER:"hover",IMPRESSION:"impression",RECEIVE_REQUEST:"receive_request",RECEIVE_RESPONSE:"receive_response",SAVE:"save",SCROLL:"scroll",SEND_REQUEST:"send_request",SEND_RESPONSE:"send_response",UNSAVE:"unsave",UPDATE:"update"})}),null);
__d("PagesLogger",["PagesLoggerEventEnum","PagesTypedLogger"],(function(a,b,c,d,e,f){var g="extra_data_",h={log:function(a,c,d,e,f,h){e===void 0&&(e=null);f===void 0&&(f=[]);var i={},j=h||{};Object.keys(j||{}).forEach(function(a){var b=j[a];(b instanceof Array||b instanceof Object)&&(b=JSON.stringify(b));i[g+a]=b});new(b("PagesTypedLogger"))().setPageID(a).setEvent(c).setEventTarget(d).setEventLocation(e).setLogSource("pages_logger").setTags(f).updateExtraData(i).log()},registerLogOnClick:function(a,c,d,e,f,g){e===void 0&&(e=null),f===void 0&&(f=[]),g===void 0&&(g={}),a.addEventListener("click",function(){h.log(c,b("PagesLoggerEventEnum").CLICK,d,e,f,g)})}};e.exports=h}),null);